apiVersion: v1
kind: Service
metadata:
  name: {{ include "retain-worker.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: retain-webhook-worker
