apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "retain-ai.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: retain-ai
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: retain-api
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: retain-webhook-worker
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
