apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "retain-ai.fullname" . }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: retain-ai
      app.kubernetes.io/instance: {{ .Release.Name }}
