apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "retain-admin.fullname" . }}
  labels:
    app.kubernetes.io/name: retain-admin
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: retain-admin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: retain-admin
    spec:
      containers:
        - name: admin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
