apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "retain-admin.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: retain-admin
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
