apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "retain-portal.fullname" . }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: retain-portal
