apiVersion: v1
kind: Service
metadata:
  name: {{ include "retain-portal.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: retain-portal
